name: Test code
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.17.0'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
